import static java.util.Arrays.fill;

import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class P8XMatrixRecovery {
	public String[] solve(String[] rowsS, String[] columnsS) {
		char[][] rows = fromString(rowsS);
		char[][] cols = fromString(columnsS);
		int n = rows.length;
		int m = cols.length;
		for (int i = 0; i < n; i++) {
			for (int j = 0; j < m; j++) {
				if (rows[i][j] == '?') {
					rows[i][j] = '0';
					if (!canDo(rows, cols)) {
						rows[i][j] = '1';
					}
				}
			}
		}
		String[] ret = new String[n];
		for (int i = 0; i < n; i++) {
			ret[i] = new String(rows[i]);
		}
		return ret;
	}

	static boolean canDo(char[][] rows, char[][] cols) {
		int n = rows.length;
		int m = cols.length;
		boolean[][] g = new boolean[m][m];
		for (int i = 0; i < m; i++) {
			all: for (int j = 0; j < m; j++) {
				for (int k = 0; k < n; k++) {
					if (!can(rows[k][i], cols[j][k])) {
						continue all;
					}
				}
				g[i][j] = true;
			}
		}
		int[] p = new int[m];
		fill(p, -1);
		boolean[] was = new boolean[m];
		int match = 0;
		for (int i = 0; i < m; i++) {
			fill(was, false);
			if (dfs(i, was, p, g)) {
				match++;
			}
		}
		return match == m;
	}
	
	static boolean dfs(int x, boolean[] was, int[] p, boolean[][] g) {
		if (was[x]) {
			return false;
		}
		was[x] = true;
		for (int i = 0; i < g[x].length; i++) {
			if (!g[x][i]) {
				continue;
			}
			if (p[i] < 0 || dfs(p[i], was, p, g)) {
				p[i] = x;
				return true;
			}
		}
		return false;
	}

	static boolean can(char c, char d) {
		return c == '?' || d == '?' || c == d;
	}

	static char[][] fromString(String[] a) {
		char[][] ret = new char[a.length][];
		for (int i = 0; i < a.length; i++) {
			ret[i] = a[i].toCharArray();
		}
		return ret;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0,
			String[] p1, boolean hasAnswer, String[] p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		P8XMatrixRecovery obj;
		String[] answer;
		obj = new P8XMatrixRecovery();
		long startTime = System.currentTimeMillis();
		answer = obj.solve(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0
				+ " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p2.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p2[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p2.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p2[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		all_right = true;

		String[] p0;
		String[] p1;
		String[] p2;

		// ----- test 0 -----
		p0 = new String[] { "10?", "?11" };
		p1 = new String[] { "01", "10", "1?" };
		p2 = new String[] { "101", "011" };
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = new String[] { "0", "?", "1" };
		p1 = new String[] { "0?1" };
		p2 = new String[] { "0", "0", "1" };
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = new String[] { "10", "01" };
		p1 = new String[] { "10", "01" };
		p2 = new String[] { "10", "01" };
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 3 -----
		p0 = new String[] { "??0", "11?", "?01", "1?1" };
		p1 = new String[] { "1???", "?111", "0?1?" };
		p2 = new String[] { "010", "110", "101", "101" };
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------

		if (all_right) {
			System.out
					.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
